# Generated by Django 3.2.5 on 2021-08-02 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='normalusercompletecode',
            fields=[
                ('author', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('editorcode_completed', models.TextField(blank=True, default='', null=True)),
                ('editorcode_completedtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('editorcode_isbasic', models.BooleanField(default=True)),
                ('editorcode_isadvance', models.BooleanField(default=False)),
                ('contract_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_contract.contractinstance')),
            ],
        ),
        migrations.CreateModel(
            name='normalusercode',
            fields=[
                ('author', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('editorcode', models.TextField(blank=True, default='', null=True)),
                ('editorcode_submittime', models.DateTimeField(default=django.utils.timezone.now)),
                ('editorcode_compile_info', models.TextField(default='')),
                ('editorcode_unittest_info', models.TextField(default='')),
                ('contract_id', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_contract.contractinstance')),
            ],
        ),
        migrations.CreateModel(
            name='normaluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_counts', models.PositiveIntegerField(default=0)),
                ('mistake_counts', models.PositiveIntegerField(default=0)),
                ('user_createtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', '男性'), ('W', '女性'), ('IPNTS', '不願意透露')], default='M', max_length=10)),
                ('age', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('education', models.CharField(choices=[('illiterate', '未受教育'), ('kindergarten', '幼稚園'), ('elementary', '小學'), ('juniorhighschool', '國中'), ('seniorhighschool', '高中'), ('university', '大學'), ('master', '碩士'), ('doctora', '博士')], default='illiterate', max_length=50)),
                ('status', models.CharField(blank=True, default='nonstatus', max_length=50, null=True)),
                ('borntime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('completed_contract_count', models.PositiveIntegerField(default=0)),
                ('guard_contract_count', models.PositiveIntegerField(default=0)),
                ('aggression_contract_count', models.PositiveIntegerField(default=0)),
                ('onetomany_contract_count', models.PositiveIntegerField(default=0)),
                ('manytomany_contract_count', models.PositiveIntegerField(default=0)),
                ('manytoone_contract_count', models.PositiveIntegerField(default=0)),
                ('unittest_contract_count', models.PositiveIntegerField(default=0)),
                ('coverage_contract_count', models.PositiveIntegerField(default=0)),
                ('mutationscore_contract_count', models.PositiveIntegerField(default=0)),
                ('basic_contract_count', models.PositiveIntegerField(default=0)),
                ('advance_contract_count', models.PositiveIntegerField(default=0)),
                ('basic_experience', models.PositiveIntegerField(default=0)),
                ('testing_experience', models.PositiveIntegerField(default=0)),
                ('advance_experience', models.PositiveIntegerField(default=0)),
                ('basic_level', models.PositiveIntegerField(default=0)),
                ('testing_level', models.PositiveIntegerField(default=0)),
                ('advance_level', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_use_normal', 'Can Use Normal'),),
            },
        ),
    ]
