# Generated by Django 3.2.5 on 2021-08-02 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_contract', '0004_auto_20210802_1010'),
        ('app_dashboard_normaluser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalusercode',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='normalusercompletecode',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normalusercode',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normalusercode',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contractinstance'),
        ),
        migrations.AlterField(
            model_name='normalusercompletecode',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normalusercompletecode',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contractinstance'),
        ),
    ]
