# Generated by Django 3.2.6 on 2022-02-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dashboard_normaluser', '0006_normalusercomplete_list_complete_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalusercomplete_list',
            name='complete_rank',
            field=models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50, null=True),
        ),
    ]
