# Generated by Django 3.2.5 on 2021-08-02 02:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tilte', models.TextField(max_length=1000)),
                ('contract_category', models.CharField(choices=[('G', 'Guard'), ('A', 'Aggression')], max_length=50)),
                ('contract_mode', models.CharField(choices=[('otm', 'OneToMany'), ('mto', 'ManyToOne'), ('mtm', 'ManyToMany')], max_length=50)),
                ('contract_oppositescount', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('contract_customer', models.CharField(default='不具名提供', max_length=50)),
                ('contract_story', models.TextField(blank=True, null=True)),
                ('contract_createtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Award',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('award_basic', models.PositiveBigIntegerField(default=0)),
                ('award_test', models.PositiveIntegerField(default=0)),
                ('award_mutant', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Content',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('content_description', models.TextField(blank=True, help_text='Enter Content Description.', max_length=10000, null=True)),
                ('content_category', models.CharField(choices=[('ut', 'Unittest'), ('cov', 'Coverage'), ('ms', 'MutationScore')], max_length=50)),
                ('content_present', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Contract_Perfect',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('perfect_description', models.TextField(blank=True, help_text='Enter Content Description.', max_length=10000, null=True)),
                ('perfect_category', models.CharField(choices=[('em', 'Empty'), ('ut', 'Unittest'), ('cov', 'Coverage'), ('ms', 'MutantScore')], max_length=50)),
                ('perfect_present', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='ContractInstance',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contract')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='award',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contract_award'),
        ),
        migrations.AddField(
            model_name='contract',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contract_content'),
        ),
        migrations.AddField(
            model_name='contract',
            name='perfect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contract_perfect'),
        ),
    ]
