# Generated by Django 3.2.5 on 2021-08-02 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_AddedTable',
            fields=[
                ('table_id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('addedtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contractinstance')),
            ],
        ),
    ]
