# Generated by Django 3.2.5 on 2021-08-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contract', '0003_contract_completedtable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract_addedtable',
            old_name='table_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='contract_completedtable',
            old_name='table_id',
            new_name='id',
        ),
    ]
