# Generated by Django 3.2.5 on 2021-08-02 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contract', '0005_auto_20210802_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_completedtable',
            name='contract_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contract.contractinstance'),
        ),
    ]
