# Generated by Django 3.2.6 on 2021-11-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contract', '0006_alter_contract_completedtable_contract_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_level',
            field=models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD'), ('strong', 'STRONG')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
