# Generated by Django 3.2.6 on 2022-02-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contract', '0008_auto_20220113_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_input_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_input_example_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_input_example_two',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_output_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_output_example_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_output_example_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
